/**
 * Emoji data for the picker.
 *
 * Stored compactly as `"<emoji> <space separated keywords>"` strings and parsed
 * once at module load into `{ char, keywords }` records.
 *
 * @module lib/emoji-data
 */

/** @type {Record<string, string[]>} */
const RAW = {
  'emoji.cat.smileys': [
    '😀 grin happy',
    '😃 smiley happy',
    '😄 smile joy',
    '😁 beam grin',
    '😆 laugh squint',
    '😅 sweat laugh',
    '🤣 rofl laugh',
    '😂 joy tears laugh',
    '🙂 slight smile',
    '🙃 upside down',
    '😉 wink',
    '😊 blush smile',
    '😇 innocent halo',
    '🥰 love hearts',
    '😍 heart eyes love',
    '🤩 star struck',
    '😘 kiss',
    '😗 kissing',
    '😚 kissing closed',
    '😋 yum tasty',
    '😛 tongue',
    '🤪 zany crazy',
    '🤨 raised brow',
    '🧐 monocle',
    '🤓 nerd geek',
    '😎 cool sunglasses',
    '🥳 party celebrate',
    '😏 smirk',
    '😒 unamused',
    '😞 disappointed sad',
    '😔 pensive sad',
    '😟 worried',
    '😕 confused',
    '🙁 frown',
    '😣 persevere',
    '😖 confounded',
    '😫 tired',
    '😩 weary',
    '🥺 pleading',
    '😢 cry sad',
    '😭 sob cry',
    '😤 triumph steam',
    '😠 angry',
    '😡 rage mad',
    '🤬 cursing',
    '🤯 mind blown',
    '😳 flushed',
    '🥵 hot',
    '🥶 cold freezing',
    '😱 scream fear',
    '😨 fearful',
    '😰 anxious',
    '🤗 hug',
    '🤔 thinking',
    '🤫 shush quiet',
    '🤥 lying',
    '😶 no mouth',
    '😐 neutral',
    '😑 expressionless',
    '😬 grimace',
    '🙄 eye roll',
    '😯 hushed',
    '😴 sleeping zzz',
    '🤤 drool',
    '😪 sleepy',
    '😷 mask sick',
    '🤒 thermometer sick',
    '🤕 bandage hurt',
    '🤢 nausea sick',
    '🤮 vomit',
    '🥱 yawn',
    '😈 devil imp',
    '👻 ghost',
    '💀 skull',
    '🤡 clown',
    '👽 alien',
    '🤖 robot bot',
    '💩 poop',
  ],
  'emoji.cat.people': [
    '👋 wave hello',
    '🤚 raised hand',
    '✋ hand stop',
    '🖖 spock',
    '👌 ok perfect',
    '🤌 pinched',
    '✌️ victory peace',
    '🤞 fingers crossed luck',
    '🤟 love you',
    '🤘 rock horns',
    '👈 point left',
    '👉 point right',
    '👆 point up',
    '👇 point down',
    '☝️ index up',
    '👍 thumbs up like',
    '👎 thumbs down dislike',
    '✊ fist',
    '👊 punch fist',
    '👏 clap applause',
    '🙌 raised hands praise',
    '🤝 handshake deal',
    '🙏 pray thanks',
    '💪 muscle strong',
    '🧠 brain',
    '👀 eyes look',
    '👤 person silhouette',
    '👶 baby',
    '🧑 person',
    '👨 man',
    '👩 woman',
    '🧓 older person',
    '👮 police',
    '🕵️ detective spy',
    '👨‍💻 developer coder',
    '👩‍💻 developer coder',
    '🧑‍🚀 astronaut',
    '🦸 superhero',
    '🧙 wizard mage',
    '🎅 santa',
    '🤷 shrug',
    '🤦 facepalm',
    '💁 info desk',
    '🙋 raising hand',
    '🙅 no gesture',
    '🙆 ok gesture',
    '💃 dancer',
    '🕺 dancing man',
    '🚶 walking',
    '🏃 running',
  ],
  'emoji.cat.nature': [
    '🐶 dog puppy',
    '🐱 cat kitten',
    '🐭 mouse',
    '🐹 hamster',
    '🐰 rabbit bunny',
    '🦊 fox',
    '🐻 bear',
    '🐼 panda',
    '🐨 koala',
    '🐯 tiger',
    '🦁 lion',
    '🐮 cow',
    '🐷 pig',
    '🐸 frog',
    '🐵 monkey',
    '🙈 see no evil monkey',
    '🐔 chicken',
    '🐧 penguin',
    '🐦 bird',
    '🦆 duck',
    '🦉 owl',
    '🦇 bat',
    '🐺 wolf',
    '🐗 boar',
    '🐴 horse',
    '🦄 unicorn',
    '🐝 bee',
    '🐛 bug caterpillar',
    '🦋 butterfly',
    '🐌 snail',
    '🐞 ladybug',
    '🐜 ant',
    '🕷️ spider',
    '🦂 scorpion',
    '🐢 turtle',
    '🐍 snake',
    '🦖 dinosaur trex',
    '🐙 octopus',
    '🦑 squid',
    '🦐 shrimp',
    '🐠 fish tropical',
    '🐬 dolphin',
    '🐳 whale',
    '🦈 shark',
    '🐊 crocodile',
    '🌵 cactus',
    '🌲 tree evergreen',
    '🌴 palm tree',
    '🌱 seedling',
    '🍀 clover luck',
    '🍁 maple leaf',
    '🌸 blossom flower',
    '🌹 rose flower',
    '🌻 sunflower',
    '🌼 daisy',
    '🌍 earth globe',
    '🌙 moon night',
    '⭐ star',
    '🌟 glowing star',
    '✨ sparkles',
    '⚡ lightning bolt',
    '🔥 fire hot',
    '🌈 rainbow',
    '☀️ sun sunny',
    '☁️ cloud',
    '🌊 wave water',
    '❄️ snowflake',
  ],
  'emoji.cat.food': [
    '🍏 green apple',
    '🍎 apple red',
    '🍐 pear',
    '🍊 orange tangerine',
    '🍋 lemon',
    '🍌 banana',
    '🍉 watermelon',
    '🍇 grapes',
    '🍓 strawberry',
    '🫐 blueberries',
    '🍒 cherries',
    '🍑 peach',
    '🥭 mango',
    '🍍 pineapple',
    '🥑 avocado',
    '🍅 tomato',
    '🌽 corn',
    '🥕 carrot',
    '🥔 potato',
    '🍞 bread',
    '🥐 croissant',
    '🥨 pretzel',
    '🧀 cheese',
    '🍗 chicken leg',
    '🥩 steak meat',
    '🍔 burger hamburger',
    '🍟 fries',
    '🍕 pizza',
    '🌭 hot dog',
    '🌮 taco',
    '🌯 burrito',
    '🥗 salad',
    '🍜 noodles ramen',
    '🍣 sushi',
    '🍤 tempura shrimp',
    '🍚 rice',
    '🥟 dumpling',
    '🍦 ice cream',
    '🍩 donut',
    '🍪 cookie',
    '🎂 birthday cake',
    '🍰 cake slice',
    '🍫 chocolate',
    '🍿 popcorn',
    '🍯 honey',
    '☕ coffee',
    '🍵 tea',
    '🧃 juice box',
    '🥤 soda cup',
    '🍺 beer',
    '🍷 wine',
    '🥂 cheers champagne',
    '🍾 bottle pop',
  ],
  'emoji.cat.activity': [
    '⚽ soccer football',
    '🏀 basketball',
    '🏈 american football',
    '⚾ baseball',
    '🎾 tennis',
    '🏐 volleyball',
    '🏓 ping pong',
    '🏸 badminton',
    '🥊 boxing',
    '⛳ golf',
    '🎯 dart target',
    '🎳 bowling',
    '🎮 gaming controller',
    '🕹️ joystick',
    '🎲 dice',
    '🧩 puzzle',
    '♟️ chess',
    '🎨 art palette',
    '🎬 clapper film',
    '🎤 microphone sing',
    '🎧 headphones',
    '🎵 music note',
    '🎹 piano keyboard',
    '🎸 guitar',
    '🥁 drum',
    '🏆 trophy win',
    '🥇 gold medal',
    '🎖️ medal',
    '🎗️ ribbon',
    '🎉 party tada',
    '🎊 confetti',
    '🎁 gift present',
    '🏅 sports medal',
    '🚴 cycling',
    '🏊 swimming',
    '🧘 yoga meditation',
  ],
  'emoji.cat.travel': [
    '🚗 car',
    '🚕 taxi',
    '🚌 bus',
    '🚑 ambulance',
    '🚓 police car',
    '🚚 truck',
    '🚲 bicycle',
    '🛵 scooter',
    '🏍️ motorcycle',
    '✈️ airplane',
    '🚀 rocket launch',
    '🛰️ satellite',
    '🚁 helicopter',
    '⛵ sailboat',
    '🚢 ship',
    '🚂 train',
    '🚇 metro subway',
    '🗺️ map',
    '🧭 compass',
    '🗿 moai',
    '🗽 statue liberty',
    '🗼 tokyo tower',
    '🏰 castle',
    '🏝️ island',
    '🏖️ beach',
    '⛰️ mountain',
    '🌋 volcano',
    '🏕️ camping',
    '🏙️ cityscape',
    '🌃 night city',
    '🌉 bridge',
    '🕌 mosque',
    '⛩️ shrine',
    '🏠 house home',
    '🏢 office building',
    '🏥 hospital',
    '🏦 bank',
    '🏫 school',
  ],
  'emoji.cat.objects': [
    '⌚ watch',
    '📱 phone mobile',
    '💻 laptop computer',
    '🖥️ desktop monitor',
    '⌨️ keyboard',
    '🖱️ mouse computer',
    '🖨️ printer',
    '💾 floppy save',
    '💿 disc',
    '📷 camera',
    '📹 video camera',
    '📺 tv',
    '📻 radio',
    '🔋 battery',
    '🔌 plug',
    '💡 bulb idea',
    '🔍 magnifier search',
    '🔒 lock secure',
    '🔓 unlock',
    '🔑 key',
    '🔨 hammer',
    '🔧 wrench',
    '⚙️ gear settings',
    '🧰 toolbox',
    '🧲 magnet',
    '💉 syringe',
    '💊 pill',
    '🩹 bandage',
    '🚪 door',
    '🛏️ bed',
    '🚿 shower',
    '🧹 broom clean',
    '🧺 basket',
    '🛒 cart shopping',
    '💰 money bag',
    '💳 credit card',
    '💎 gem diamond',
    '📦 package box',
    '📫 mailbox',
    '✉️ envelope mail',
    '📝 memo note',
    '📄 page document',
    '📊 bar chart',
    '📈 chart up',
    '📉 chart down',
    '📅 calendar',
    '📌 pin',
    '📎 paperclip',
    '✂️ scissors',
    '📚 books',
    '📖 open book',
    '🔖 bookmark',
    '🏷️ label tag',
    '✏️ pencil',
    '🖊️ pen',
    '🖌️ paintbrush',
    '🧮 abacus',
    '⏰ alarm clock',
    '⏳ hourglass',
    '🔔 bell notification',
    '📢 loudspeaker announce',
  ],
  'emoji.cat.symbols': [
    '❤️ red heart love',
    '🧡 orange heart',
    '💛 yellow heart',
    '💚 green heart',
    '💙 blue heart',
    '💜 purple heart',
    '🖤 black heart',
    '🤍 white heart',
    '💔 broken heart',
    '❣️ heart exclamation',
    '💕 two hearts',
    '💞 revolving hearts',
    '💯 hundred perfect',
    '✅ check done',
    '☑️ ballot check',
    '✔️ check mark',
    '❌ cross wrong',
    '⭕ circle',
    '❗ exclamation',
    '❓ question',
    '⚠️ warning',
    '🚫 prohibited',
    '♻️ recycle',
    '🔰 beginner',
    '⚜️ fleur de lis',
    '🔱 trident',
    '⚛️ atom',
    '☢️ radioactive',
    '➕ plus',
    '➖ minus',
    '✖️ multiply',
    '➗ divide',
    '🟰 equals',
    '♾️ infinity',
    '🔢 numbers',
    '🔠 letters',
    '🅰️ a button',
    '🆎 ab button',
    '🆗 ok button',
    '🆕 new',
    '🆓 free',
    '🔝 top',
    '🔜 soon',
    '⏩ fast forward',
    '⏪ rewind',
    '⏫ up',
    '⏬ down',
    '▶️ play',
    '⏸️ pause',
    '⏹️ stop',
    '🔀 shuffle',
    '🔁 repeat',
    '🔴 red circle',
    '🟠 orange circle',
    '🟡 yellow circle',
    '🟢 green circle',
    '🔵 blue circle',
    '🟣 purple circle',
    '⚫ black circle',
    '⚪ white circle',
    '🔺 red triangle',
    '🔻 down triangle',
    '💠 diamond',
    '🔘 radio button',
    '🏁 checkered flag',
    '🚩 flag',
    '🏳️ white flag',
    '🏴 black flag',
  ],
};

/**
 * @typedef {{ char: string, keywords: string }} EmojiRecord
 */

/**
 * Parsed emoji categories.
 * @type {Array<{ id: string, emojis: EmojiRecord[] }>}
 */
export const EMOJI_CATEGORIES = Object.entries(RAW).map(([id, entries]) => ({
  id,
  emojis: entries.map((entry) => {
    const spaceAt = entry.indexOf(' ');
    return spaceAt === -1
      ? { char: entry, keywords: '' }
      : { char: entry.slice(0, spaceAt), keywords: entry.slice(spaceAt + 1) };
  }),
}));

/**
 * Search all categories by keyword.
 * @param {string} query
 * @returns {EmojiRecord[]}
 */
export function searchEmoji(query) {
  const q = (query || '').trim().toLowerCase();
  if (!q) return [];
  const seen = new Set();
  const out = [];
  for (const category of EMOJI_CATEGORIES) {
    for (const emoji of category.emojis) {
      if (seen.has(emoji.char)) continue;
      if (emoji.keywords.includes(q) || emoji.char === q) {
        seen.add(emoji.char);
        out.push(emoji);
      }
    }
  }
  return out;
}
