/**
 * Stylesheet guards.
 *
 * The renderer loads every stylesheet into one cascade, so a class name reused
 * by two unrelated components silently inherits the other's layout. That is
 * exactly how the table bubble menu once turned the live-preview bubble into a
 * flex row and broke its text into one character per line — these tests keep
 * that class of bug from coming back.
 */
import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';

const STYLE_DIR = path.resolve(__dirname, '../../src/renderer/styles');

/** Classes intentionally styled from more than one file. */
const SHARED_OWNERS = new Set(['editor-pane']);

/** @returns {Array<{ file: string, css: string }>} */
function readStylesheets() {
  return fs
    .readdirSync(STYLE_DIR)
    .filter((name) => name.endsWith('.css'))
    .map((name) => ({
      file: name,
      css: fs.readFileSync(path.join(STYLE_DIR, name), 'utf8').replace(/\/\*[\s\S]*?\*\//g, ''),
    }));
}

/**
 * Collect the "owning" class of every rule — the first class in each selector,
 * which is the one whose box the rule lays out.
 * @returns {Map<string, Set<string>>} class → files
 */
function ownersByClass() {
  const owners = new Map();
  for (const { file, css } of readStylesheets()) {
    for (const selectorList of css.match(/[^{}]+(?=\{)/g) || []) {
      for (const selector of selectorList.split(',')) {
        const match = selector.trim().match(/\.([a-zA-Z][\w-]*)/);
        if (!match) continue;
        const cls = match[1];
        if (!owners.has(cls)) owners.set(cls, new Set());
        owners.get(cls).add(file);
      }
    }
  }
  return owners;
}

describe('stylesheets', () => {
  it('give every class a single owning file', () => {
    const clashes = [];
    for (const [cls, files] of ownersByClass()) {
      if (files.size > 1 && !SHARED_OWNERS.has(cls)) {
        clashes.push(`.${cls} → ${[...files].sort().join(', ')}`);
      }
    }
    expect(clashes).toEqual([]);
  });

  it('keeps the preview bubble free of the table bubble layout', () => {
    const sheets = Object.fromEntries(readStylesheets().map((s) => [s.file, s.css]));
    expect(sheets['menu.css']).not.toMatch(/^\.bubble\s*\{/m);
    expect(sheets['menu.css']).toMatch(/\.table-bubble\s*\{/);
    expect(sheets['preview.css']).toMatch(/\.bubble\s*\{/);
  });

  it('balances every brace', () => {
    for (const { file, css } of readStylesheets()) {
      const open = (css.match(/\{/g) || []).length;
      const close = (css.match(/\}/g) || []).length;
      expect(open, `${file} braces`).toBe(close);
    }
  });

  it('declares no leftover class that no component uses', () => {
    const componentSource = fs
      .readdirSync(path.resolve(__dirname, '../../src/renderer/components'))
      .filter((f) => f.endsWith('.jsx') || f.endsWith('.js'))
      .map((f) =>
        fs.readFileSync(path.resolve(__dirname, '../../src/renderer/components', f), 'utf8'),
      )
      .join('\n');
    const appSource = fs.readFileSync(path.resolve(__dirname, '../../src/renderer/App.jsx'), 'utf8');
    const markup = `${componentSource}\n${appSource}`;

    // Classes generated by TipTap/ProseMirror or set on <body>/<html> instead.
    const external = /^(ProseMirror|tiptap|tfr-editor|is-editor-empty|selectedCell|column-resize-handle|light|details-content|tg-|pv-|language-)/;

    const unused = [];
    for (const [cls] of ownersByClass()) {
      if (external.test(cls)) continue;
      if (!markup.includes(cls)) unused.push(cls);
    }
    expect(unused).toEqual([]);
  });
});
